// Tab: INDUSTRY. Root (D1, Basic Extractor) je sam u tier 1, sve tri linije granaju se iz njega.
// line: 'A' Mining & Extraction, 'B' Smelting & Materials, 'C' Assembly & Manufacturing.
export const INDUSTRY_NODES = [
  {
    id: 'D1', title: 'Basic Extractor', tier: 1, cost: 0, prerequisites: [],
    description: 'Unlocks the Extractor building - the start of every production chain.',
    effect: null,
  },

  // --- Line A: Mining & Extraction ---
  { id: 'D2', title: 'Advanced Mining', line: 'A', tier: 2, cost: 20, prerequisites: ['D1'],
    description: 'Extractor speed +30%.', effect: (ctx) => { ctx.modifiers.extractorSpeedMultiplier *= 1.3; } },
  { id: 'D3', title: 'Deep Drilling', line: 'A', tier: 3, cost: 0, prerequisites: ['D2'],
    description: '[Not in game yet / unverified] Oil & gas extraction. 0RP until confirmed and, if needed, a dedicated node is added.',
    effect: null, placeholder: true },
  { id: 'D4', title: 'Forestry & Lumbering', line: 'A', tier: 4, cost: 0, prerequisites: ['D1'],
    description: '[Not in game yet] Logging - a new raw resource. 0RP until the industry exists.',
    effect: null, placeholder: true },
  { id: 'D5', title: 'Automated Extraction', line: 'A', tier: 5, cost: 160, prerequisites: ['D2'],
    description: 'All extractors (existing and future) no longer require power.',
    effect: (ctx) => { ctx.modifiers.extractorPowerExempt = true; for (const e of ctx.state.extractors) e.requiresPower = false; } },
  { id: 'D6', title: 'Prospecting Survey', line: 'A', tier: 6, cost: 0, prerequisites: ['D5'],
    description: '[Not in game yet] Reveals higher-richness resource deposits on the map. 0RP until the system exists.',
    effect: null, placeholder: true },
  { id: 'D7', title: 'Autonomous Mining Drones', line: 'A', tier: 7, cost: 0, prerequisites: ['D6'],
    description: '[Not in game yet] Further extraction automation. 0RP until the system exists.',
    effect: null, placeholder: true },

  // --- Line B: Smelting & Materials ---
  { id: 'D8', title: 'Basic Smelter', line: 'B', tier: 2, cost: 20, prerequisites: ['D1'],
    description: 'Unlocks the Smelter building.', effect: null },
  { id: 'D9', title: 'Alloy Production', line: 'B', tier: 3, cost: 0, prerequisites: ['D8'],
    description: '[Not in game yet] Alloys (steel, bronze) - new recipes. 0RP until the recipes exist.',
    effect: null, placeholder: true },
  { id: 'D10', title: 'Chemical Processing', line: 'B', tier: 4, cost: 0, prerequisites: ['D9', 'D3'],
    description: '[Not in game yet] Chemicals/plastics - new recipes, depends on oil (Deep Drilling). 0RP until the recipes exist.',
    effect: null, placeholder: true },
  { id: 'D11', title: 'Advanced Metallurgy', line: 'B', tier: 5, cost: 0, prerequisites: ['D9'],
    description: '[Not yet wired up] Reduces smelting raw-material consumption by 15% - waiting on a Processor class change. 0RP until connected.',
    effect: null, placeholder: true },
  { id: 'D12', title: 'High-Tech Foundry', line: 'B', tier: 6, cost: 300, prerequisites: ['D11'],
    description: 'Processor speed (smelter/factory/assembler) +50%.', effect: (ctx) => { ctx.modifiers.processorSpeedMultiplier *= 1.5; } },
  { id: 'D13', title: 'Automated Quality Control', line: 'B', tier: 7, cost: 0, prerequisites: ['D12'],
    description: '[Not in game yet] Reduces defect/waste rate during processing. 0RP until the system exists.',
    effect: null, placeholder: true },

  // --- Line C: Assembly & Manufacturing ---
  { id: 'D14', title: 'Basic Assembler', line: 'C', tier: 2, cost: 20, prerequisites: ['D1'],
    description: 'Unlocks the Assembler building.', effect: null },
  { id: 'D15', title: 'Advanced Factory', line: 'C', tier: 3, cost: 45, prerequisites: ['D14'],
    description: 'Unlocks the Factory building.', effect: null },
  { id: 'D16', title: 'Precision Tools', line: 'C', tier: 4, cost: 0, prerequisites: ['D15'],
    description: '[Not in game yet] Recipes for electronics/motors. 0RP until the recipes exist.',
    effect: null, placeholder: true },
  { id: 'D17', title: 'Heavy Machinery Plant', line: 'C', tier: 5, cost: 0, prerequisites: ['D16'],
    description: '[Not in game yet] Recipes for industrial assemblies. 0RP until the recipes exist.',
    effect: null, placeholder: true },
  { id: 'D18', title: 'Overclocking', line: 'C', tier: 6, cost: 0, prerequisites: ['D17'],
    description: '[Not in game yet] Temporary factory speed boost at the cost of higher power draw. 0RP until the system exists.',
    effect: null, placeholder: true },
  { id: 'D19', title: 'Modular Assembly Lines', line: 'C', tier: 7, cost: 0, prerequisites: ['D18'],
    description: '[Not in game yet] Parallel assembly lines for higher throughput. 0RP until the system exists.',
    effect: null, placeholder: true },
];
