// Tab: INFRASTRUCTURE. Root (I1) je sam u tier 1, sve tri linije granaju se iz njega.
// line: 'A' Roads & Traffic, 'B' Bridges & Marine, 'C' Power Grid.
export const INFRASTRUCTURE_NODES = [
  {
    id: 'I1', title: 'Gravel Road', tier: 1, cost: 0, prerequisites: [],
    description: 'The most basic road surface. Unlocks the road-building tool.',
    effect: null,
  },

  // --- Line A: Roads & Traffic (each tier is its own road surface) ---
  { id: 'I2', title: 'Dirt Road', line: 'A', tier: 2, cost: 20, prerequisites: ['I1'],
    description: 'Unlocks the Dirt Road surface (faster than gravel).', effect: null },
  { id: 'I3', title: 'Asphalt Paving', line: 'A', tier: 3, cost: 45, prerequisites: ['I2'],
    description: 'Unlocks Asphalt (fastest road surface, 2x speed vs. dirt).', effect: null },
  { id: 'I4', title: 'Traffic Signals', line: 'A', tier: 4, cost: 0, prerequisites: ['I3', 'L8'],
    description: '[Not in game yet] Automatic traffic signals at busy intersections. 0RP until the system exists.',
    effect: null, placeholder: true },
  { id: 'I5', title: 'Expressways', line: 'A', tier: 5, cost: 0, prerequisites: ['I4'],
    description: '[Not in game yet] Multi-lane roads (new geometry model). 0RP until the system exists.',
    effect: null, placeholder: true },
  { id: 'I6', title: 'Grade Separated Junctions', line: 'A', tier: 6, cost: 0, prerequisites: ['I5'],
    description: '[Not in game yet] Overpasses (road over road). 0RP until the system exists.',
    effect: null, placeholder: true },
  { id: 'I7', title: 'Smart Traffic AI', line: 'A', tier: 7, cost: 0, prerequisites: ['I6'],
    description: '[Not in game yet] Adaptive signal timing that reacts to live congestion. 0RP until the system exists.',
    effect: null, placeholder: true },

  // --- Line B: Bridges & Marine ---
  { id: 'I8', title: 'Wooden Bridges', line: 'B', tier: 2, cost: 20, prerequisites: ['I1'],
    description: 'Unlocks the wooden bridge (first tier, water crossing).', effect: null },
  { id: 'I9', title: 'Concrete Bridges', line: 'B', tier: 3, cost: 45, prerequisites: ['I8'],
    description: 'Unlocks the concrete bridge (second tier).', effect: null },
  { id: 'I10', title: 'Steel Girder Bridges', line: 'B', tier: 4, cost: 90, prerequisites: ['I9'],
    description: 'Unlocks the steel bridge (third, fastest tier).', effect: null },
  { id: 'I11', title: 'Deep Water Ports & Shipping', line: 'B', tier: 5, cost: 0, prerequisites: ['I10'],
    description: '[Not in game yet] Ship entity + port capacity (goods wait for a ship instead of an instant sale). 0RP until the system exists.',
    effect: null, placeholder: true },
  { id: 'I12', title: 'Land Reclamation', line: 'B', tier: 6, cost: 0, prerequisites: ['I11'],
    description: '[Not in game yet] Permanently fills in shallow water as land. 0RP until the system exists.',
    effect: null, placeholder: true },
  { id: 'I13', title: 'Container Terminals', line: 'B', tier: 7, cost: 0, prerequisites: ['I12'],
    description: '[Not in game yet] Larger port throughput/capacity. 0RP until the system exists.',
    effect: null, placeholder: true },

  // --- Line C: Power Grid ---
  { id: 'I14', title: 'Basic Generators', line: 'C', tier: 2, cost: 20, prerequisites: ['I1'],
    description: 'Unlocks the Power Plant building (fixed output, 50 power).', effect: null },
  { id: 'I15', title: 'Power Substation', line: 'C', tier: 3, cost: 45, prerequisites: ['I14'],
    description: 'Unlocks the Power Pole - links plants/batteries/consumers into a grid.', effect: null },
  { id: 'I16', title: 'Battery Storage', line: 'C', tier: 4, cost: 90, prerequisites: ['I15'],
    description: 'Unlocks the Battery building (stores surplus power, covers shortfalls).', effect: null },
  { id: 'I17', title: 'Renewable Energy', line: 'C', tier: 5, cost: 0, prerequisites: ['I14'],
    description: '[Not in game yet] Wind/solar plants, free to run. 0RP until the variant exists.',
    effect: null, placeholder: true },
  { id: 'I18', title: 'High-Voltage Grid', line: 'C', tier: 6, cost: 0, prerequisites: ['I15'],
    description: '[Not in game yet] Reduces transmission losses. 0RP until losses exist in the model.',
    effect: null, placeholder: true },
  { id: 'I19', title: 'Smart Grid Management', line: 'C', tier: 7, cost: 0, prerequisites: ['I16'],
    description: '[Not in game yet] Automatic load balancing across multiple power networks. 0RP until the system exists.',
    effect: null, placeholder: true },
];
