export const CONFIG = {
  TILE_SIZE: 24,
  CAMERA_ZOOM_MIN: 0.4,
  CAMERA_ZOOM_MAX: 3,
  WORLD_WIDTH: 120,
  WORLD_HEIGHT: 80,
  WORLD_SEED: 42,
  TRUCK_COST: 300,
  TRUCK_SELL_REFUND: 150,
  ALLOW_DIRECT_CONVEYOR_SALE: false,
};
